YAHOO_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'

# modules and time schemes
QUOTESUMMARY_MODULES = {
    "summaryProfile": 60, # contains general information about the company",
    "summaryDetail": 60, # prices + volume + market cap + etc",
    "assetProfile": 60, # summaryProfile + company officers",
    "fundProfile": 60, # ",
    "price": 60, # current prices",
    "quoteType": 60, # quoteType",
    "esgScores": 60, # Environmental, social, and governance (ESG) scores, sustainability and ethical performance of companies",
    "incomeStatementHistory": 60, # ",
    "incomeStatementHistoryQuarterly": 60, # ",
    "balanceSheetHistory": 60, # ",
    "balanceSheetHistoryQuarterly": 60, # ",
    "cashFlowStatementHistory": 60, # ",
    "cashFlowStatementHistoryQuarterly": 60, # ",
    "defaultKeyStatistics": 60, # KPIs (PE, enterprise value, EPS, EBITA, and more)",
    "financialData": 60, # Financial KPIs (revenue, gross margins, operating cash flow, free cash flow, and more)",
    "calendarEvents": 60, # future earnings date",
    "secFilings": 60, # SEC filings, such as 10K and 10Q reports",
    "upgradeDowngradeHistory": 60, # upgrades and downgrades that analysts have given a company"s stock",
    "institutionOwnership": 60, # institutional ownership, holders and shares outstanding",
    "fundOwnership": 60, # mutual fund ownership, holders and shares outstanding",
    "majorDirectHolders": 60, # ",
    "majorHoldersBreakdown": 60, # ",
    "insiderTransactions": 60, # insider transactions, such as the number of shares bought and sold by company executives",
    "insiderHolders": 60, # insider holders, such as the number of shares held by company executives",
    "netSharePurchaseActivity": 60, # net share purchase activity, such as the number of shares bought and sold by company executives",
    "earnings": 60, # earnings history",
    "earningsHistory": 60, # ",
    "earningsTrend": 60, # earnings trend",
    "industryTrend": 60, # ",
    "indexTrend": 60, # ",
    "sectorTrend": 60, # ",
    "recommendationTrend": 60, # ",
    "futuresChain": 60, # ",
}
